import { Metadata } from "next";
// اینجا میتونیم برای هر صفحه خودمون متا دیتای کاستوم خودمون رو قرار بدیم
export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
  keywords: "test1 , test2 , test3",
};

const Store = () => {
  return <div>Store Page</div>;
};

export default Store;
